[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swifey = "DRHbVragqmDceUKDRPdu8ogSZbNFAbcherr3PZ2CZ8Nt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = './id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
